### ISSUE TITLE
Unable to launch tmtdt

### ISSUE THREAD

**Issue by jleseane23** [kquinsland/the-missing-todoist-tools#7]
## The problem

When trying to run the demo job file using the following command `python tmtdt.py --job-file jobs\demo\00.setup.yaml`

I get the following error:
`Traceback (most recent call last):
  File "tmtdt.py", line 244, in <module>
    launch(args)
  File "tmtdt.py", line 42, in launch
    valid_actions = validate_job_file(job_file)
  File "c:\HTPC\Apps\tmtdt\the-missing-todoist-tools\tdt\utils\config.py", line 117, in validate_job_file
    job_file = get_job_file(job_file_path)
  File "c:\HTPC\Apps\tmtdt\the-missing-todoist-tools\tdt\utils\config.py", line 175, in get_job_file
    return yaml.load(utils.read_file(job_file), Loader=yaml.FullLoader)
  File "c:\HTPC\Apps\tmtdt\the-missing-todoist-tools\tdt\utils\__init__.py", line 22, in read_file
    return handle.read()
  File "C:\Users\Biggamal\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 279: character maps to <undefined>`

## Environment

- TMTDT version: `v0.0.1-6d3c9cc-20200915`
- Python version: `Python 3.7.7`  
- Operating environment (OS/Container/Supervised/Core): Windows 10 2004
 
## job-file 

```yaml
# Paste your job-file here
`##
# Sets up a 'blank' ToDoist account for demo :)
##
version: 1

actions:
  - name: demo-setup-projects
    action: project_create
    enabled: Yes
    description: >-
      Creates Simple 'root' project

    projects:
      - from:
          name: 'Garage Sale 🏚️💵'
        color: PURPLE

  - name: demo-setup-tasks-1
    action: task_create
    enabled: Yes
    description: >-
      Creates example tasks for our garage sale

    items:
      - content: "Old Lamp 🛋️"
        project:
          name: "Garage Sale 🏚️💵"
      - content: "Kids Clothes"
        project:
          name: "Garage Sale 🏚️💵"
      - content: "Old Exercise Equipment"
        project:
          name: "Garage Sale 🏚️💵"

  - name: demo-setup-tasks
    action: task_create
    enabled: Yes
    description: >-
      Creates example tasks for our inbox

    items:
      - content: "Ask boss about a raise at work"
      - content: "Practice big presentation at the office"

  - name: demo-setup-labels
    action: label_create
    enabled: Yes
    description: >-
      Creates example labels for our inbox

    labels:
      - label: "at_work"
        color: RED
        favorite: Yes`

## Traceback/Error logs
<!--
  If you come across any trace or error logs, please provide them.
-->

```txt
paste the output or content of the TMTDT log file here
`unable to launch the script to generate log files`

## Additional information

Provide any additional information here if you have it

**Comment by kquinsland** [comment]
`cp1252.py` and `UnicodeDecodeError` have me thinking that this is related to windows using a default encoding for text other than what the rest of the world uses as a default encoding.

A little bit of google [later](https://docs.python.org/3/library/functions.html#open):

```
encoding is the name of the encoding used to decode or encode the file. This should only be used in text mode. The default encoding is platform dependent (whatever locale.getpreferredencoding() returns), but any text encoding supported by Python can be used. See the codecs module for the list of supported encodings.
```

Can you open a python shell and tell me what `locale.getpreferredencoding()` returns?

It'll look something like this:


```shell
$ python3
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getpreferredencoding()
'UTF-8'
```


I'm willing to bet that you _don't_ get `'UTF-8'`.

**Comment by jleseane23** [comment]
You're right.

I got `cp1252` instead.

I'm not familiar with python but I know my way around a shell. I'll google to see how it can be changed

**Comment by kquinsland** [comment]
> I got `cp1252` instead.


Ok, that's good news, then.  If you didnt get that, i'd have no idea what the problem is.

It'll be a little bit before I can push a proper change, but you should be able to modify this line:

https://github.com/kquinsland/the-missing-todoist-tools/blob/6d3c9ccc7f101a14cf9d1d0dfe55b2fc1de0d27a/tdt/utils/__init__.py#L21

**from:** 
```with open(file, 'r') as handle:```

**to:**
 ```with open(file, 'r', encoding='utf-8') as handle:```


and that should get things playing nicely.

**Comment by jleseane23** [comment]
That did the trick! Thanks again.

I got some errors when I tried to run the demo log but I'm going to clear the cache and try to make my own job file first to make sure it wasn't a one off.
